<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AquariusREPL</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AquariusLangInterpreted\AquariusLangInterpreted.csproj" />
      <Content Include="runtimes/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="AquariusLangTesting" />
    </ItemGroup>

</Project>
