<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>AquariusLang.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.17.2" />
    <PackageReference Include="Wasmtime" Version="48.0.2" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-x64" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-arm64" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.osx-x64" Version="7.5.1.1" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.osx-arm64" Version="7.5.1.1" />
    <PackageReference Include="Silk.NET.WebGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Native.WGPU" Version="2.23.0" />
    <ProjectReference Include="../AquariusCore/AquariusCore.csproj" />
    <ProjectReference Include="../AquariusPackaging/AquariusPackaging.csproj" />
    <Content Include="runtimes/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="licenses/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="../AquariusCore/external/jolt/vendor-jolt.LICENSE.txt" Link="licenses/JOLT-WASM-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(NuGetPackageRoot)microsoft.clearscript.v8/7.5.1.1/licenses/**/*" Link="licenses/clearscript/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="examples/**/*"
             Exclude="examples/**/.idea/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="AquariusTests" />
  </ItemGroup>
</Project>
