<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>AquariusREPL</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.17.2" />
    <PackageReference Include="JoltPhysicsSharp" Version="2.19.1" />
    <PackageReference Include="JoltPhysics.Native" Version="1.0.4" />
    <PackageReference Include="Silk.NET.WebGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.23.0" />
    <PackageReference Include="Silk.NET.WebGPU.Native.WGPU" Version="2.23.0" />
    <ProjectReference Include="../AquariusLangVM/AquariusLangVM.csproj" />
    <ProjectReference Include="../AquariusPackaging/AquariusPackaging.csproj" />
    <Content Include="runtimes/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="licenses/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="examples/**/*"
             Exclude="examples/**/.idea/**/*"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="AquariusLangVMTesting" />
  </ItemGroup>
</Project>
