"""Regenerate the complete Aquarius OpenGL 3.3 core API from the vendored GLAD header.

No Python packages or network access are needed. To update GLAD itself, use glad2
2.0.8 with: --api gl:core=3.3 --extensions= --reproducible c
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parent
header = (root / 'vendor/glad/include/glad/gl.h').read_text()
types = {'void': 'void', 'GLenum': 'uint', 'GLuint': 'uint', 'GLbitfield': 'uint',
         'GLint': 'int', 'GLsizei': 'int', 'GLboolean': 'byte', 'GLbyte': 'sbyte',
         'GLubyte': 'byte', 'GLshort': 'short', 'GLushort': 'ushort',
         'GLfloat': 'float', 'GLdouble': 'double', 'GLintptr': 'IntPtr',
         'GLsizeiptr': 'IntPtr', 'GLsync': 'IntPtr', 'GLint64': 'long', 'GLuint64': 'ulong'}

def managed(t):
    return 'IntPtr' if '*' in t else types[t]

typedefs = {name: (ret.strip(), params) for ret, name, params in re.findall(
    r'typedef (.+?) \(GLAD_API_PTR \*(PFNGL\w+PROC)\)\((.*?)\);', header)}
entries = re.findall(r'GLAD_API_CALL (PFNGL\w+PROC) glad_(gl\w+);', header)
cs = ['// Generated by native/generate_bindings.py; do not edit.',
      'using System.Runtime.InteropServices;', 'namespace AquariusREPL.Graphics;',
      'internal sealed partial class GraphicsRuntime {', '    private void RegisterGl() {']
delegates = []
c = ['/* Generated GLAD function table. */']
for signature, name in entries:
    ret, params = typedefs[signature]
    arguments = [] if params == 'void' else params.split(',')
    native_types = [re.sub(r'\s*\w+$', '', p.strip()).strip() for p in arguments]
    descriptors = ', '.join('"' + t + '"' for t in native_types)
    cs.append(f'        BindGl("{name}", typeof(D_{name}), "{ret}", new string[] {{ {descriptors} }});')
    delegates.extend(['    [UnmanagedFunctionPointer(CallingConvention.Winapi)]',
        f'    private delegate {managed(ret)} D_{name}(' + ', '.join(
            f'{managed(t)} a{i}' for i, t in enumerate(native_types)) + ');'])
    c.append(f'    if (strcmp(name, "{name}") == 0) return (GLADapiproc)glad_{name};')
for name, value in re.findall(r'^#define (GL_\w+) (0x[0-9A-Fa-f]+|[0-9]+)\s*$', header, re.M):
    integer = int(value, 0)
    if integer <= 0xFFFFFFFF:
        cs.append(f'        GlEnvironment.Create("{name}", new AquariusLang.Object.DoubleObj({integer}d));')
cs.extend(['    }'] + delegates + ['}'])
(root / 'gl_table.inc').write_text('\n'.join(c) + '\n')
(root.parent / 'AquariusDesktopVMREPL/graphics/GlBindings.Generated.cs').write_text('\n'.join(cs) + '\n')
print(f'Generated {len(entries)} OpenGL entry points.')
