<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>aqua</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AquariusBuild/AquariusBuild.csproj" />
    <ProjectReference Include="../AquariusPackaging/AquariusPackaging.csproj" />
    <ProjectReference Include="../AquariusDesktopVMREPL/AquariusDesktopVMREPL.csproj" />
    <ProjectReference Include="../AquariusWebCompiler/AquariusWebCompiler.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../build-targets/**/*" Exclude="../build-targets/.aquarius-*/**/*" Link="build-targets/%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
