<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <RootNamespace>AquariusLang.Compiler</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="wasm/runtime/runtime.wasm" LogicalName="AquariusLang.Wasm.runtime.wasm" />
    <EmbeddedResource Include="external/jolt/*" LogicalName="AquariusLang.External.jolt.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
